
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-control-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: control-api
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000
    protocol: TCP