apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-role-binding
  namespace: flink
subjects:
- kind: ServiceAccount
  name: flink
  namespace: flink
roleRef:
  kind: Role
  name: flink-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: control-api-role-binding
  namespace: control-api
subjects:
- kind: ServiceAccount
  name: control-api
  namespace: control-api
roleRef:
  kind: Role
  name: control-api-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-role-binding
  namespace: kafka
subjects:
- kind: ServiceAccount
  name: strimzi-cluster-operator
  namespace: kafka
roleRef:
  kind: ClusterRole
  name: strimzi-cluster-operator-namespaced
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: observability-role-binding
  namespace: observability
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: observability
roleRef:
  kind: Role
  name: prometheus-role
  apiGroup: rbac.authorization.k8s.io